version: "2"

services:
  web_scripts:
    image: goalgorilla/open_social_docker:ci
    volumes:
     - ./:/var/www
    environment:
     - DRUPAL_SETTINGS=production
    network_mode: "bridge"
    container_name: social_ci_web_scripts

  web:
    image: goalgorilla/open_social_docker:ci
    volumes:
     - ./:/var/www
    links:
     - db:db
     - mailcatcher:mailcatcher
     - redis
    environment:
     - DRUPAL_SETTINGS=production
    ports:
     - "80"
    network_mode: "bridge"
    container_name: social_ci_web

  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
     - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    network_mode: "bridge"
    container_name: social_ci_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.social.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"
    container_name: social_mailcatcher

  selenium:
    image: selenium/standalone-firefox:2.48.2
    links:
     - web:web
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files
    ports:
     - "4444"
     - "5900"
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"
    container_name: social_ci_selenium

  behat:
    image: goalgorilla/open_social_docker:ci
    volumes:
     - ./:/var/www
    links:
     - web:web
     - db:db
     - selenium:selenium
     - mailcatcher:mailcatcher
    environment:
     - DRUPAL_SETTINGS=production
    network_mode: "bridge"
    container_name: social_ci_behat

  redis:
    image: redis:latest
    network_mode: "bridge"

volumes:
  db_data:
